DROP TABLE IF EXISTS tasc_prod.tasc_products_shopify CASCADE;
CREATE TABLE tasc_prod.tasc_products_shopify (
    id SERIAL PRIMARY KEY,
    parent_product_id VARCHAR(255),
    child_product_id VARCHAR(255),
    product_title VARCHAR(255),
    product_desc TEXT,
    handle VARCHAR(255),
    vendor VARCHAR(255),
    product_type VARCHAR(255),
    tags TEXT,
    published_at TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    variant_title VARCHAR(255),
    sku VARCHAR(255),
    price DECIMAL(10, 2),
    grams INT,
    available BOOLEAN,
    requires_shipping BOOLEAN,
    taxable BOOLEAN,
    featured_image TEXT,
    position INT,
    sizes TEXT,
    product_image_1_url TEXT,
    product_image_2_url TEXT,
    product_image_3_url TEXT,
    product_image_4_url TEXT,
    product_image_5_url TEXT,
    asof_dt DATE,
    created_at_tms TIMESTAMP,
    created_by VARCHAR(255),
    last_modified_tms TIMESTAMP,
    last_modified_by VARCHAR(255),
    source_date DATE,
    source_datetime TIMESTAMP
);